// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsN-e1iwfXVO2L0LHlsM2plbdJiIvcEO4',
    appId: '1:118380008019:android:eb4a6d31b3a07fc05feca6',
    messagingSenderId: '118380008019',
    projectId: 'smart-attendance-system-d6ed0',
    databaseURL: 'https://smart-attendance-system-d6ed0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-attendance-system-d6ed0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyprqgDsD2OLvCkIKolVQdoGTLKZD_Jg',
    appId: '1:118380008019:web:8f50cf3d1e281e3f5feca6',
    messagingSenderId: '118380008019',
    projectId: 'smart-attendance-system-d6ed0',
    authDomain: 'smart-attendance-system-d6ed0.firebaseapp.com',
    databaseURL: 'https://smart-attendance-system-d6ed0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-attendance-system-d6ed0.firebasestorage.app',
  );

}